[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "poetry run python -m src.main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckTimeout = 30
